
namespace BookShop.Models
{
    public class BookRepository : IBookRepository
    {
        private readonly IGenreRepository _genreRepository = new GenreRepository();
        public IEnumerable<Book> GetAll => new List<Book>
        {
            new Book{bookId = 1, shortDescritpion="Încă de la apariţie, în 1948, în revista Sur a Victoriei Ocampo, romanul Tunelul s-a bucurat, de aprecierile elogioase ale unor mari scriitori ca Thomas Mann, Graham Greene şi Albert Camus, autorul fiind considerat un „clasic existenţialist“.", title="Tunelul", author="Ernesto Sabato", publisher="Humanitas Fiction", price = 24.00, inStock = true, imgUrl = @"\Images\1stBook.jpg", description = "Încă de la apariţie, în 1948, în revista Sur a Victoriei Ocampo, romanul Tunelul s-a bucurat, de aprecierile elogioase ale unor mari scriitori ca Thomas Mann, Graham Greene şi Albert Camus, autorul fiind considerat un „clasic existenţialist“.\r\n\r\nRoman tulburător şi captivant despre dragoste şi moarte, întemeiat pe o investigaţie existenţială a dramei determinate de imposibilitatea comunicării cu semenii, de solitudinea iremediabilă a individului şi mai cu seamă a artistului, de abisul halucinant dintre puritate şi nebunie, Tunelul este confesiunea pictorului Juan Pablo Castel. Din închisoare, acesta decide să relateze faptele şi să dezvăluie motivele obscure care l-au determnat s-o omoare pe María Iribarne. Sondând cu rigoare magistrală condiţia tragică a omului contemporan, izvorâtă din credinţa excesivă în raţiune, Sabato descrie modul în care un artist sensibil şi talentat ajunge treptat, sub imperiul propriilor demoni lăuntrici, de la obsesia atotstăpânitoare pentru dragostea absolută la gelozie (auto)distrugătoare, apoi la nebunie şi crimă.", publishYear = 1948, genre = _genreRepository.allGenres.ToList()[0]},
            new Book{bookId = 2, shortDescritpion="Ultimul mare mit al literaturii argentiniene, stins din viaţă în 2011, cu puţin înainte de a împlini o sută de ani, Ernesto Sabato este creatorul unei opere proteice, care conţine în esenţă eternele contradicţii şi frământări ale fiinţei umane şi ale societăţii, circumscrise unui univers artistic şi spiritual de o tulburătoare profunzime şi originalitate.", title="Despre eroi si morminte", author="Ernesto Sabato", publisher="Humanitas Fiction", price = 30.00, inStock = true, imgUrl = @"\Images\2ndBook.jpg", description = "Ultimul mare mit al literaturii argentiniene, stins din viaţă în 2011, cu puţin înainte de a împlini o sută de ani, Ernesto Sabato este creatorul unei opere proteice, care conţine în esenţă eternele contradicţii şi frământări ale fiinţei umane şi ale societăţii, circumscrise unui univers artistic şi spiritual de o tulburătoare profunzime şi originalitate.\r\n\r\n„În romanul meu am încercat să surprind realitatea în toată extinderea şi profunzimea ei, înglobând nu doar partea diurnă a existenţei, ci şi pe aceea nocturnă şi tenebroasă. Întrucât Fernando Vidal este personajul central şi precumpănitor, tot ce se referea la el era important şi trebuia descris... Raportul reprezintă marele coşmar trăit de el, exprimând, chiar dacă simbolic şi oarecum incert, miezul cel mai semnificativ al condiţiei şi existenţei sale. Dacă aş fi suprimat această parte din roman, din considerente legate de coerenţa logică, ar fi însemnat să suprim visele oamenilor, care aparţin viziunii lor integrale asupra vieţii.“ (Ernesto SABATO)\r\n\r\nAdevărată capodoperă, Despre eroi şi morminte (1961), cel de-al doilea volet al trilogiei care începe cu Tunelul (1948) şi se încheie cu Abaddon, exterminatorul (1974), este un roman total, extrem de dens, scris cu credinţa mărturisită de autor că „nu se poate trăi fără eroi, sfinţi şi martiri\", şi că „prezentul generează trecutul“. Trei planuri se întrepatrund, într-un joc fascinant de umbre şi lumini, în complexa sa structura narativă de voci alternante, întemeiată pe împletirea istoriei naţionale argentiniene cu drama individuală: povestea de dragoste între Martín şi Alejandra, trecutul glorios dezgropat din morminte, reconsiderat printr-o radiografie a Argentinei contemporane, şi obsedanta temă a orbirii şi a nebuniei din celebrul Raport despre Orbi.", publishYear = 1961, genre = _genreRepository.allGenres.ToList()[1]},
            new Book{bookId = 3, shortDescritpion="Un roman complex, care relevă momente esenţiale din istoria lumii, împletind povestirea filozofică, eseul şi elementul autobiografic într-o capodoperă a literaturii universale.", title="Abaddon exterminatorul", author="Ernesto Sabato", publisher="Humanitas Fiction", price = 45.28, inStock = true, imgUrl = @"\Images\3rdBook.jpg", description = "Un roman complex, care relevă momente esenţiale din istoria lumii, împletind povestirea filozofică, eseul şi elementul autobiografic într-o capodoperă a literaturii universale.\r\n\r\n„Când m-am apucat să scriu cel de-al treilea roman, care în final avea să devină Abaddon exterminatorul, intenţia mea era să construiesc un roman despre roman, un fel de roman la puterea a doua. Voiam să scriu ceva care să fie în acelaşi timp ficţiune, dar şi o dezbatere asupra ficţiunii, un fel de anchetă asupra formei înseşi a genului, asupra posibilităţilor, a limitelor, a secretului izvoarelor sale în adâncul sufletului omenesc.“ (Ernesto SABATO)\r\n\r\nUnul dintre cele mai cutremurătoare romane ale secolului XX, ultima parte a trilogiei care mai cuprinde Tunelul şi Despre eroi şi morminte, Abaddon exterminatorul este o creaţie densă, vizionară, de un intelectualism rafinat. Într-un Buenos Aires terorizat de dictatura militară de la începutul anilor '70, o serie de semne nefaste, de premoniţii şi evenimente inexplicabile par să anunţe o inevitabilă apocalipsă. Un vagabond clarvăzător zăreşte un semn pe care numai el pare să-l înţeleagă: un dragon cu şapte capete vărsând flăcări pe cerul înserării, un tânăr idealist e torturat şi ucis de poliţie, care îl bănuieşte de subversiune, agenţi ai Răului par să se fi răspândit pretutindeni şi, treptat, peste lumea lipsită de speranţă se înstăpâneşte puterea tenebrelor.", publishYear = 1974, genre = _genreRepository.allGenres.ToList()[2]},
            new Book{bookId = 4, shortDescritpion="Una dintre capodoperele literaturii universale, \"Divina Comedie\", a exercitat o puternica influenta asupra culturii, artei si literaturii intregii lumi. \"Infernul\", prima parte a acestei trilogii, reprezinta calatoria lui Dante prin cele noua cercuri ale iadului.", title="Infernul", author="Dante Aligheri", publisher="RAO", price = 30.28, inStock = true, imgUrl = @"\Images\imgBook4.png", description = "Una dintre capodoperele literaturii universale, \"Divina Comedie\", a exercitat o puternica influenta asupra culturii, artei si literaturii intregii lumi. \"Infernul\", prima parte a acestei trilogii, reprezinta calatoria lui Dante prin cele noua cercuri ale iadului. El isi incepe peregrinarea in jurul anului 1307, iar ghid pe acest drum presarat de primejdii ii este idolul sau, poetul roman Virgiliu, care il conduce spre poarta infernului.\r\n\r\nPe parcursul calatoriei sale, Dante va intalni numeroase personalitati, filosofi sau figuri mitice ale Antichitatii, dar si oameni care au trait in vremea sa. Acest din urma amestec de locuri imaginare si experiente concrete reprezinta unul dintre marile talente ale poetului, care descrie cu multa forta si realism toate aceste personaje celebre.", publishYear = 2013, genre = _genreRepository.allGenres.ToList()[2]},
            new Book{bookId = 5, shortDescritpion="„O scriere fabuloasa, fastuoasa, somptuoasa, narcotica, [...] o proza [...] in care sangele se distileaza periodic pana ajunge parfum si tot ce e greu devine usor pentru a pluti...“ (Dan Stanca, Romania libera)", title="Orbitor", author="Mircea Cartarescu", publisher="Humanitas Fiction", price = 80.28, inStock = true, imgUrl = @"\Images\bookImg5.jpg", description = "„O scriere fabuloasa, fastuoasa, somptuoasa, narcotica, [...] o proza [...] in care sangele se distileaza periodic pana ajunge parfum si tot ce e greu devine usor pentru a pluti...“ (Dan Stanca, Romania libera)\r\n\r\n„O desfatare lingvistica, o carte in care limba ofera un spectacol uluitor, fara egal.“ (Marius Chivu, Romania libera)", publishYear = 2007, genre = _genreRepository.allGenres.ToList()[2]},
            new Book{bookId = 5, shortDescritpion="„O scriere fabuloasa, fastuoasa, somptuoasa, narcotica, [...] o proza [...] in care sangele se distileaza periodic pana ajunge parfum si tot ce e greu devine usor pentru a pluti...“ (Dan Stanca, Romania libera)", title="Orbitor", author="Mircea Cartarescu", publisher="Humanitas Fiction", price = 80.28, inStock = true, imgUrl = @"\Images\bookImg5.jpg", description = "„O scriere fabuloasa, fastuoasa, somptuoasa, narcotica, [...] o proza [...] in care sangele se distileaza periodic pana ajunge parfum si tot ce e greu devine usor pentru a pluti...“ (Dan Stanca, Romania libera)\r\n\r\n„O desfatare lingvistica, o carte in care limba ofera un spectacol uluitor, fara egal.“ (Marius Chivu, Romania libera)", publishYear = 2007, genre = _genreRepository.allGenres.ToList()[2]},
            new Book{bookId = 5, shortDescritpion="„O scriere fabuloasa, fastuoasa, somptuoasa, narcotica, [...] o proza [...] in care sangele se distileaza periodic pana ajunge parfum si tot ce e greu devine usor pentru a pluti...“ (Dan Stanca, Romania libera)", title="Orbitor", author="Mircea Cartarescu", publisher="Humanitas Fiction", price = 80.28, inStock = true, imgUrl = @"\Images\bookImg5.jpg", description = "„O scriere fabuloasa, fastuoasa, somptuoasa, narcotica, [...] o proza [...] in care sangele se distileaza periodic pana ajunge parfum si tot ce e greu devine usor pentru a pluti...“ (Dan Stanca, Romania libera)\r\n\r\n„O desfatare lingvistica, o carte in care limba ofera un spectacol uluitor, fara egal.“ (Marius Chivu, Romania libera)", publishYear = 2007, genre = _genreRepository.allGenres.ToList()[2]}
        };
        

        public Book? getBookById(int id) => GetAll.FirstOrDefault(b => b.bookId == id);
        
    }
}
